Repository juice-shop/multi-juicer, pull requests merged in 2020-01, with the labels that each got.

#29 Automatic cleanup of JuiceShop on uninstall
  juice-balancer/src/kubernetes.js
  readme.md
Labels: enhancement

#30 Rename Project to MultiJuicer
  cleaner/readme.md
  cover.svg
  e2e/cypress/integration/juice_balancer_spec.js
  e2e/package-lock.json
  e2e/package.json
  guides/aws/aws.md
  guides/azure/azure.md
  guides/digital-ocean/digital-ocean.md
  guides/digital-ocean/do-lb.yaml
  guides/openshift/openshift-helm-overrides.yaml
  guides/openshift/openshift.md
  helm/multi-juicer/.helmignore
  helm/multi-juicer/Chart.lock
  helm/multi-juicer/Chart.yaml
  helm/multi-juicer/charts/redis-9.2.2.tgz
  helm/multi-juicer/templates/NOTES.txt
  helm/multi-juicer/templates/_helpers.tpl
  helm/multi-juicer/templates/cleanup-chron-job.yaml
  helm/multi-juicer/templates/cleanup-role.yaml
  helm/multi-juicer/templates/cleanup-rolebinding.yaml
  helm/multi-juicer/templates/cleanup-service-account.yaml
  helm/multi-juicer/templates/juice-balancer-config-map.yaml
  helm/multi-juicer/templates/juice-balancer-deployment.yaml
  helm/multi-juicer/templates/juice-balancer-role-binding.yaml
  helm/multi-juicer/templates/juice-balancer-role.yaml
  helm/multi-juicer/templates/juice-balancer-secret.yaml
  helm/multi-juicer/templates/juice-balancer-service-account.yaml
  helm/multi-juicer/templates/juice-balancer-service.yaml
  helm/multi-juicer/templates/juice-shop-config-map.yaml
  helm/multi-juicer/values.yaml
  juice-balancer/config/config.json
  juice-balancer/package.json
  juice-balancer/src/kubernetes.js
  juice-balancer/ui/package.json
  juice-balancer/ui/public/index.html
  juice-balancer/ui/src/Layout.js
  progress-watchdog/go.mod
  readme.md
Labels: breaking

#31 Added AWS Guide
  guides/aws/alb-ingress-controller.yaml
  guides/aws/aws-ingress.yaml
  guides/aws/aws.md
  guides/aws/cluster-iam.yaml
  readme.md
Labels: documentation

#36 Decrease default cleanup history limit to 1
  helm/multi-juicer/templates/cleanup-chron-job.yaml
  helm/multi-juicer/values.yaml
Labels: enhancement
