Repository juice-shop/multi-juicer, pull requests merged in 2020-04, with the labels that each got.

#46 Adding some more steps / debugging notes
  guides/aws/aws.md
Labels: documentation

#48 Use actual Namespace in progress-watchdog
  progress-watchdog/main.go
Labels: bug

#50 Added a template to configure an ingress rule for the multijuicer
  helm/multi-juicer/Chart.yaml
  helm/multi-juicer/templates/_helpers.tpl
  helm/multi-juicer/templates/juice-balancer-deployment.yaml
  helm/multi-juicer/templates/juice-balancer-ingress.yaml
  helm/multi-juicer/templates/juice-balancer-service.yaml
  helm/multi-juicer/values.yaml
Labels: helm
